import { Book } from './models/book.model';
import { User } from './models/user.model';

export const USER_LIST: User[] = [
  {
    id: 'usr_001',
    family_name: 'Толстой',
    name: 'Лев',
    middle_name: 'Николаевич',
    reg_date: new Date(2024, 0, 15), // 15 января 2024
  },
  {
    id: 'usr_002',
    family_name: 'Достоевский',
    name: 'Фёдор',
    middle_name: 'Михайлович',
    reg_date: new Date(2024, 0, 20),
  },
  {
    id: 'usr_003',
    family_name: 'Чехова',
    name: 'Анна',
    middle_name: 'Павловна',
    reg_date: new Date(2024, 1, 5),
  },
  {
    id: 'usr_004',
    family_name: 'Булгаков',
    name: 'Михаил',
    middle_name: 'Афанасьевич',
    reg_date: new Date(2024, 1, 10),
  },
  {
    id: 'usr_005',
    family_name: 'Цветаева',
    name: 'Марина',
    reg_date: new Date(2024, 1, 18),
  },
  {
    id: 'usr_006',
    family_name: 'Есенин',
    name: 'Сергей',
    middle_name: 'Александрович',
    reg_date: new Date(2024, 2, 1),
  },
  {
    id: 'usr_007',
    family_name: 'Ахматова',
    name: 'Анна',
    middle_name: 'Андреевна',
    reg_date: new Date(2024, 2, 12),
  },
  {
    id: 'usr_008',
    family_name: 'Набоков',
    name: 'Владимир',
    middle_name: 'Владимирович',
    reg_date: new Date(2024, 2, 25),
  },
  {
    id: 'usr_009',
    family_name: 'Гоголь',
    name: 'Николай',
    middle_name: 'Васильевич',
    reg_date: new Date(2024, 3, 3),
  },
  {
    id: 'usr_010',
    family_name: 'Тургенева',
    name: 'Ирина',
    middle_name: 'Сергеевна',
    reg_date: new Date(2024, 3, 14),
  },
  {
    id: 'usr_011',
    family_name: 'Шолохов',
    name: 'Михаил',
    reg_date: new Date(2024, 3, 22),
  },
  {
    id: 'usr_012',
    family_name: 'Грибоедова',
    name: 'Софья',
    middle_name: 'Александровна',
    reg_date: new Date(2024, 4, 1),
  },
  {
    id: 'usr_013',
    family_name: 'Лермонтов',
    name: 'Михаил',
    middle_name: 'Юрьевич',
    reg_date: new Date(2024, 4, 9),
  },
  {
    id: 'usr_014',
    family_name: 'Пушкина',
    name: 'Наталья',
    middle_name: 'Николаевна',
    reg_date: new Date(2024, 4, 17),
  },
  {
    id: 'usr_015',
    family_name: 'Островский',
    name: 'Александр',
    middle_name: 'Николаевич',
    reg_date: new Date(2024, 4, 28),
  },
];

export const BOOK_LIST: Book[] = [
  {
    id: 'bk_001',
    title: '451 градус по Фаренгейту',
    author: 'Рэй Брэдбери',
    pub_year: 1953,
    taken: false,
    comment: 'Научно-фантастический роман',
  },
  {
    id: 'bk_002',
    title: 'Гарри Поттер и философский камень',
    author: 'Дж.К. Роулинг',
    pub_year: 1997,
    taken: true,
    comment: 'Детская литература',
  },
  {
    id: 'bk_003',
    title: '1984',
    author: 'Джордж Оруэлл',
    pub_year: 1949,
    taken: false,
    comment: 'Антиутопия',
  },
  {
    id: 'bk_004',
    title: 'Убить пересмешника',
    author: 'Харпер Ли',
    pub_year: 1960,
    taken: true,
    comment: 'Пулитцеровская премия',
  },
  {
    id: 'bk_005',
    title: 'Великий Гэтсби',
    author: 'Фрэнсис Скотт Фицджеральд',
    pub_year: 1925,
    taken: false,
    comment: 'Американская классика',
  },
  {
    id: 'bk_006',
    title: 'Над пропастью во ржи',
    author: 'Джером Сэлинджер',
    pub_year: 1951,
    taken: true,
    comment: '',
  },
  {
    id: 'bk_007',
    title: 'Маленький принц',
    author: 'Антуан де Сент-Экзюпери',
    pub_year: 1943,
    taken: false,
    comment: 'С иллюстрациями автора',
  },
  {
    id: 'bk_008',
    title: 'Граф Монте-Кристо',
    author: 'Александр Дюма',
    pub_year: 1844,
    taken: false,
    comment: 'В 2 томах',
  },
  {
    id: 'bk_009',
    title: 'Три товарища',
    author: 'Эрих Мария Ремарк',
    pub_year: 1936,
    taken: true,
    comment: 'Продление бронирования',
  },
  {
    id: 'bk_010',
    title: 'Сто лет одиночества',
    author: 'Габриэль Гарсиа Маркес',
    pub_year: 1967,
    taken: false,
    comment: 'Магический реализм',
  },
];
